---
title: "rbasic_20190906_106_kim.Rmd"
output: html_notebook
---
## 3.2 The very basics

Before we get started with the motivating dataset, we need to cover the very basics of R. 

### 3.2.1 Objects

Suppose a high school student asks us for help solving several quadratic equations of the form
$ax^2+bx+c=0$.
The quadratic formula gives us the solutions:
$$
{{-b-\sqrt{b^2-4ac}}\over{2a}}
\text{and}
{{-b+\sqrt{b^2-4ac}}\over{2a}}
$$

which of course change depending on the values of $a$, $b$ and $c$. One advantage of programming languages is that we can define variables and write expresstions with these variables, similar to how we do so in math, but obtain a numeric solution. We will write out general code for the quadratic equation below, but if we are asked to solve $x^2+x-1=0$, then we define:

~~~{r}
a <- 1
b <- 1
c <- -1
~~~

which stores the values for later use. We use `<-` to assign values to the variables.

We can also assign values using `=` instead of `<-`, but we recommend against using `=` to avoid confusion.

Copy and paste the code above into your console to define the three variables. Note that R does not print anything when we make this assignment. This means the objects were definded successfully. Had you made a mistake, you would have received an error message.

To see the value stored in a variable, we simply ask R to evaulate `a` and it shows the stored value:

~~~{r}
  a
  #> [1] 1
~~~

A more explicit way to ask R to show us the value stored in `a` is using `print` like this:

~~~{r}
  print(a)
  #> [1] 1
~~~

We use the term *object* to describe stuff that is stored in R. Variables are examples, but objects can also be more complicated entities such as functions, which are described later.

### 3.2.2 The workspace

As we define objects in the console, we are actually changing the *workspace*. You can see all the variables saved in your workspace by typing:

~~~{r}
  ls()
  #> [1] "a" "b" "c" "img_path" "murders"
~~~

In RStudio, the *Environment* tab shows the values:

We should see `a`, `b`, and `c`. If you try to recover the value of a variable that is not in your workspace, you receive an err. For example, if you type `x` you will receive the following message: `Error: object 'x' not found`.

Now since these values are saved in variables, to obtain a solution to our equation, we use the quadratic formula:

~~~{r}
  (-b + sqrt(b^2 - 4*a*c) ) / ( 2*a )
  #> [1] 0.618034
  (-b - sqrt(b^2 - 4*a*c) ) / ( 2*a )
  #> [1] -1.618034
~~~

### 3.2.3 Functions

Once you define variables, the data analysis process can ususally be described as a series of *fuctions* applied to the data. R includes several predefined functions and most of the analysis pipelines we construct make extensive use of these.

We already used the `install.packages`, `library`, and `ls` functions. We also used the function `sqrt` to solve the quadratic eqation above. There are many more prebuilt functions and even more can be added through packages. These functions do noy appear in the workspace because you did not define them, but they are available for immediate use.

In general, we need to use parentheses to evalutate a function. If you type `ls`, the funciton is not evaluated and instead R shows you the code that defines the function. If you type `ls()` the function is evaluated and, as seen above, we see objects in the workspace.

Unlike `ls`most functions require one or more *arguments*. Below is an example of how we assign an object to the argument of thefunciton `log`. Remeber that we earlier defined `a` to be 1:

~~~{r}
  log(8)
  #> [1] 2.079442
  log(a)
  #> [1] 0
~~~

You can find out what the function expects and what it does by reviewing the very useful manuals included in R. You can gey help by using the `help` function like this:

~~~{r}
help("log")
~~~

For most functions, we can also use this shorthand:

~~~{r}
?log
~~~

The help page will show you what arguments the function is expecting. For example, `log` needs `x` and `base` to run. However, some arguments are required and others are optional. You cna determine shich arguments are optional by noitng in the help document that a default value is assign with `=`. Defining these is optinal. For example, the base of the function `log` defaults to `base = exp(1)` making `log `the natural log by default.

If you want a quick look at the arguments without opening the help system, you can type:

~~~{r}
  args(log)
  #> function (x, base = exp(1)) 
  #> NULL
~~~

You can change the default values by simply assigning another object:

~~~{r}
  log(8, base = 2)
  #> [1] 3
~~~

Note that we have not been specifying the argument `x` as such:

~~~{r}
  log(x = 8, base = 2)
  # [1] 3
~~~

The above code works, but we can save ourselves some typing: if no argument name is used, R assumes you are entering arguments in the order shown in the help file or by `args`. So by not using the names, it assumes the arguments are `x` followed by `base`:

~~~{r}
  log(8,2)
  #> [1] 3
~~~

If using the arguments' names, then we can include them in whatever order we want:

~~~{r}
  log(base = 2, x = 8)
  #> [1] 3
~~~

To specify arguments, we must use `=`, and cannot use `<-`.

There are some exceptions to the rule that functions need the parentheses to be evalutaed. Among these, the most commonly used are the arithmetic and relational operators. For example:

~~~{r}
  2 ^ 3
  #> [1] 8
~~~

You can see the arithmetic operators by typing:

~~~{r}
help("+")
~~~

or

~~~{r}
?"+"
~~~

and the relational operators by typing:

~~~{r}
help(">")
~~~

or

~~~{r}
?">"
~~~

### 3.2.4 Other prebuilt objects

There are several datasets that are inclueded for users to pratice and test out funcitons. You can see all the available datasets by typing:

~~~{r}
data()
~~~

This shows you the object name for these datases. These datasets are objects that can be used by simply typing the name. For example, if you type:

~~~{r}
co2
~~~

R will show you Mauna Loa atmospheric CO2 concentration data.

Other prebuilt objects are mathematical qauntities, such as the constant $\pi$ and $\infty$:

~~~{r}
  pi
  #> [1] 3.141593
  Inf+1
  #> [1] Inf
~~~

### 3.2.5 Variable names

We have used the letters `a`, `b` and `c`as variable names, but variable names can be almost anything. Some basic rules in R are that variable names have to start with a letter, can't contain spaces and should not be variables that are predefined in R. For example. don't name one of your variables `install.packages` by typing something like `install.packages <- 2`.

A nice convention to follow is to use meaningful words that describe what is stored, use only lower case, and use underscores as a subtitute for spaces. For the quadratic equation, we could use something like this:

~~~{r}
solution_1 <- (-b + sqrt(b^2 - 4*a*c)) / (2*a)
solution_2 <- (-b - sqrt(b^2 - 4*a*c)) / (2*a)
~~~

For more advice, we highly recommend stidying [Hardley Wickham's style guide](http://adv-r.had.co.nz/Style.html).

### 3.2.6 Saving your workspace

Values remain in the workspace until you end your session or erase them with the function `rm`. But workspaces also can be saved for later use. In fact, when you quit R, the program asks you if you want to asave your workspace. If you do save it, the next time you start R, the program will restore the workspace.

We actually recommend against saving the workspace this way because, as you start working on diffent projects, it will become harder to keep track of what is saved. Instead, we recommnd you assing the workspace a specific name. You can do this by using the function `save` or `save.image`. To load, use the function `load`. When saving a workspace, we recommend the suffix `rda` or `RData`. In RStudio, you can alsodo this by navigating to the *Session* tab and choosing *
Save Workspace as*. You can later load it using the *Load Workspace* options in the same tab. You can read the help pages on `save`, `save.image` and `load` to learn more.

### 3.2.7 Motivating scripts

To solve another equation such as $3x^2 + 2x - 1$, we can copy and paste the code above and then redefine the variables and recompute the solution:

~~~{r}
a <- 3
b <- 2
c <- -1
(-b + sqrt(b^2 - 4*a*c)) / (2*a)
(-b - sqrt(b^2 - 4*a*c)) / (2*a)
~~~

By creating and saving a script with the code above, we would not need to retype everything each time and, instead, simply change the variable names. Try writing the script above into an editor and notice how easy it is to change the varialbes and receive an answer.

### 3.2.8 Commenting your code

If a line of R code starts with the symbol `#`, it is not evaluted. We can use this write reminders of why we wrote particular code. Forexmaple, in the script above we could add:

~~~{r}
  ## Code to compute solution to quadratic equation of the form ax^2 + bx + c
  ## define the variables
a <- 3
b <- 2
c <- -1

  ## now compute the solution
(-b + sqrt(b^2 - 4*a*c)) / (2*a)
(-b - sqrt(b^2 - 4*a*c)) / (2*a)
~~~

## 3.3 Exercises

1. What is the sum of the first 100 positive integers? The formular for the sum of integers $1$ through $n$ is $n(n + 1) / 2$. Define $n = 100$ and then use R to compute the sum of $1$ through $100$ using the formula. What is the sum?

2. Now use the same formula to compute the sum of the integers from 1 through 1,000.

3. Look at the result of typing the following code into R:

~~~{r}
n <- 1000
x <- seq(1, n)
sum(x)
~~~

Based on the result, what do you think the functions `seq` and `sum` do? You can use the `hlep` system: 

A. `sum` creates a list of numbers and `seq` adds them up.

B. `seq` creates a list of numbers and `sum` adds them up.

C. `seq` computes the difference between two arguments and `sum` computes the sum of 1 through 1000.

D. `sum` always returns the same number.  

4. In math and programming, we say that we evaluate a function when we replace the argument with a given number. So if we type `sqrt(4)`, we evalutate the `sqrt` function. In R, you can evaluate a function inside another function. The evaluations happen from the inside out.

5. Which of the following will always return the numeric value stored in `x`? You can try out examples and use the help system if you want.

A. `log(10^x)`

B. `log10(x^10)`

C. `log(exp(x))`

D. `exp(log(x, base = 2))`

## 3.4 Data types

Variables in R can be of different types For example, we need to distinguish numbers from character strings and tables from simple lists of numbers. The function `class` helps us determine what type of object we have:

~~~{r}
a <- 2
class(a)
  #> [1] "numeric"
~~~

To work efficiently in R, is is important to learn the differnet types of variables and what we can do with these.

## 3.5 Data frames

Up to now, the variables we have defined are just one number. This is not very useful for storing data. The most common way of storing a dataset in R is in a *data frame*. Conceptually, we can think of a data frame as a table with rows representing observations and the different variables reported for each observation defining the columns. Data frames are particularly useful for datasets because we can combine different data types into one object.

A large proportion of data analysis challenges start with data stored in a data frame. For example, we stored the data for our motivating example in a data frame. You can access this dataset by loading the **dslabs** library and loading the `murders` dataset using the `data` function:

~~~{r}
  library{dslab}
  data{murders}
~~~

To see that is in fact a data frame, we type:

~~~{r}
  class(muerders)
  #> [1] "data.frame"
~~~

### 3.5.1 Examining an object

The function `str` is useful for finding out more about the structure of an object

~~~{r}
  str(murders)
  #> 'data.frame':    51 obs. of  5 variables:
  #>  $ state     : chr  "Alabama" "Alaska" "Arizona" "Arkansas" ...
  #>  $ abb       : chr  "AL" "AK" "AZ" "AR" ...
  #>  $ region    : Factor w/ 4 levels "Northeast","South",..: 2 4 4 2 4 4 1 2 2 2 ...
  #>  $ population: num  4779736 710231 6392017 2915918 37253956 ...
  #>  $ total     : num  135 19 232 93 1257 ...
~~~

This tells us much more about the object. We see that the table has 51 rows (50 states plus DC) and five variables. We can show the first six lines using the fucntion `head`:

~~~{r}
  head(murders)
  #>        state abb region population total
  #> 1    Alabama  AL  South    4779736   135
  #> 2     Alaska  AK   West     710231    19
  #> 3    Arizona  AZ   West    6392017   232
  #> 4   Arkansas  AR  South    2915918    93
  #> 5 California  CA   West   37253956  1257
  #> 6   Colorado  CO   West    5029196    65
~~~

In this dataset, each state us considered an observation and five variables are reported for each state.

Before we go any further in answering our original question about different states, let's learn more about the components of this object.

### 3.5.2 The accessor: `$`

For our analysis, we will need to access the different variables represented by columns included in this data frame. To do this, we use the accessor operator `$` in the following way:

~~~{r}
  murders$population
  #>  [1]  4779736   710231  6392017  2915918 37253956  5029196  3574097
  #>  [8]   897934   601723 19687653  9920000  1360301  1567582 12830632
  #> [15]  6483802  3046355  2853118  4339367  4533372  1328361  5773552
  #> [22]  6547629  9883640  5303925  2967297  5988927   989415  1826341
  #> [29]  2700551  1316470  8791894  2059179 19378102  9535483   672591
  #> [36] 11536504  3751351  3831074 12702379  1052567  4625364   814180
  #> [43]  6346105 25145561  2763885   625741  8001024  6724540  1852994
  #> [50]  5686986   563626
~~~

But how did we know to use population? Previously, by applying the function `str` to the object `murders`, we revealed the names for each of the five variables stored in this table. We can quickly access the variable names using:

~~~{r}
  names(murders)
  #> [1] "state"      "abb"        "region"     "population" "total"
~~~

It is important to know that the order of the entries in `murders$population` preserves the order of the rows in our data table. This will later permit us to manipulate one variable based on the results of another. For example, we will be able to order the state names by the number of murders.

**Tip**: R comes with a very nide auto-complete functionality that saves us the trouble of typing out all the names. Try typing `murders$p` then hitting the *tab* key on your keyboard. This functionality and many other useful auto-complete features are available when working in RStudio.

### 3.5.3 Vectors: numerics, characters, and logical

The object `murders$population` is not one number but several. We call these types of objects *vectors*. A single number is technically a vector of lenght 1, but in general we use the term vectors to refer to objects with several entries. The function `length` tells you how many entries are in the vector:

~~~{r}
  pop <- murders$population
  length(pop)
  #> [1] 51
~~~

This particular vector is *numeric* since population sizes are numbers:

~~~{r}
  class(pop)
  #> [1] "numeric"
~~~

In a numeric vector, every entry must be a number.

To store character strings, vectors can also be of class *character*. For example, the state names are characters:

~~~{r}
  class{murders$state}
  #> [1] "character"
~~~

As with numeric vectors, all entries in a character vector need to be character.

Another important type of vectors are *logical vectors*. These must be either `TRUE` of `FALSE`.

~~~{r}
  z <- 3 == 2
  z
  #> [1] FALSE
  class(z)
  #> [1] "lpgical"
~~~

Here the `==` is a relational operator asking if 3 is equak to 2. In R, if you just one `=`, you actually assign a variable, but it you test for equality.

You can see the other *relational operators* by typing:

~~~{r}
  ?comparison
~~~

In future section, you will see how useful relational operators can be.

We discuss more important features of vectors after the next set of exercises.

**Advanced**: Mathematically, the values in `pop` are integers and there is an integer class in R. However, by default, numbers are assigned class numeric even when they are round integers. For example, `class(1)` returns numeric, You can turn them into class integer with the `as.integer()` function or by adding an `L` like this: `1L`. Note the class by typing: `class(1L)`

### 3.5.4 Factors

In the `murders` dataset, we might expect the region to also be a character vector. However, it is not:

~~~{r}
  class(murders$region)
  #> [1] "factor"
~~~

It is a *factor*. Factors are useful for storing categorical data. We can see that there are only 4 regions by using the `levels` function:

~~~{r}
  levels(murders$region)
  #> [1] "Northeast"     "South"         "North Central" "West" 
~~~

In the background, R stores these *levels* as integers and keep a map to keep track of the labels. This is more memory efficient than storing all the characters.

Note that the lvels have an order that is different from the order of appearance in the factor object. The default is for the levels to follow alphabetical order. However, often we want the levels to follow a different order. We will see several examples of this in the Data Visulalization part of the book. The function `reorder` lets us change the order of the levels of a factor variable based on a summary computed on a numeric vector. We will demonstrate this with a simple example.

