---
title: "rbasic_20190909_106_kim"
output: html_notebook
---

<style type="text/css">

body, td {
   font-size: 14px;
   font-family: 'Nanum Gothic', sans-serif;
}
code.r{
  font-size: 12px;
  font-family: 'Roboto', sans-serif;
}
pre {
  font-size: 12px
  font-family: 'Nanum Gothic', sans-serif;
}
</style>


# Chapter 4 Programming basics

We teach R because it greatly facilitates data analyisis, the main topic of this book. By coding in R, we can efficiently perform exploratory data analysis, build data analysis pipelines and prepare data visualization to communicate results. However, R is not just a data analysis envrionment but a programming language. Advanced R programmers can develop complex packages and even improve R itself, but we do not cover advanced programming in this book. Nonetheless, in this section, we introduce three key programming concepts: conditional expressions, for-loops and functions. These are not just key building blocks for advanced programming, but are sometimes useful during data analysis. We also note that there are several functions that are widely used to program in R but that we will not cover in this book. These include `split`, `cut`, `do.call` and `Reduce`. These are worth learning if you plan to become an expert R programmer.

## 4.1 Conditional expressions

Conditional expressions are one of the basic features of programming. They are used for what is called *flow control*. The most common conditional expression is the if-else statement. In R, we can actually perform quite a bit of data analysis without conditionals. However, they do come up occasionally, and you will need them once you start writing your own functions and packages.

Here is a very simple example showing the general structure of an if-else statement. The basic idea is to print the reciprocal of `a` unless `a` is 0:

~~~{r}
a <- 0

if(a!=0){
  print(1/a)
} else{
  print("No reciprocal for 0.")
}

[1] "No reciprocal for 0."
~~~

Let's look at one more example using the US murders data frame:

~~~{r}
library(dslabs)
data(murders)
murder_rate <- murders$total / murders$population*100000
~~~

Here is a very simple example that tells us which states, if any, have a murder rate lower than 0.5 per 100,000. The `if` statement protects us from the case in which no state satisfies the condition.

~~~{r}
ind <- which.min(murder_rate)

if(murder_rate[ind] < 0.5){
  print(murders$state[ind])
} else{
  print("No state has murder rate that low")
}

[1] "Vermont"
~~~

<span style="color:red">
`which.min`이라는 funciton뜻 더 알아볼 것.
</span>

If we try it again with a rate of 0.25, we get a different answer:

~~~{r}
if(murder_rate[ind] < 0.5){
  print(murders$state[ind])
} else{
  print("No state has murder rate that low")
}
[1] "No state has murder rate that low"
~~~

A related function that is very useful is `ifelse`. This funciton takes three arguments: a logical and two possible answers. If the logical is `TRUE`, the value in the second argument is returened and if `FALSE`, the value in the third argument is returened. Here is an example:

~~~{r}
a <- 0
ifelse(a > 0, 1/a, NA)
[1] NA
~~~

The function is particularly useful because it works on vectors. It examines each of the logical vector and returns elements from the vector provided in the second argument, if the entry is `TRUE`, or elements from the vector provided in the third argument, if the entry is `FALSE`.

~~~{r}
a <- c(0,1,2,-4,5)
result <- ifelse(a > 0, 1/a, NA)
~~~

This table helps us see what happened:

<table>
  <thead>
    <tr>
      <th>a</th>
      <th>is_a_positive</th>
      <th>answer1</th>
      <th>answer2</th>
      <th>result</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>0</td>
      <td>FALSE</td>
      <td>Inf</td>
      <td>NA</td>
      <td>NA</td>
    </tr>
    <tr>
      <td>1</td>
      <td>TURE</td>
      <td>1.00</td>
      <td>NA</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>2</td>
      <td>TRUE</td>
      <td>0.50</td>
      <td>NA</td>
      <td>0.5</td>
    </tr>
    <tr>
      <td>-4</td>
      <td>FALSE</td>
      <td>-0.25</td>
      <td>NA</td>
      <td>NA</td>
    </tr>
    <tr>
      <td>5</td>
      <td>TRUE</td>
      <td>0.20</td>
      <td>NA</td>
      <td>0.2</td>
    </tr>
  </tbody>
</table>

a	| is_a_positive	| answer1 |	answer2 |	result 
--|---------------|---------|---------|-------
0	| FALSE	| Inf	| NA	| NA  
1	| TRUE	| 1.00	| NA	| 1.0  
2	| TRUE	| 0.50	| NA	| 0.5  
-4	| FALSE	| -0.25	| NA	| NA  
5	| TRUE	| 0.20	| NA	| 0.2

Here is an example of how this funciton can be readily used to replace all the missing values in a vector with zeros:

~~~{r}
data(na_exmaple)
no_nas <- ifelse(is.na(na_example), 0, na_example)
sum(is.na(no_nas))
[1] 0
~~~

<span style="color:red">
`is.na()`라는 함수를 잘 모르겠음.
</span>

Two other useful functions are `any` and `all`. The `any` function takes a vector of logicals and returns `TRUE` if any of the entries is `TRUE`. The `all` fuction takes a vector of logcials and returns `TRUE` if all of the entries are `TRUE`. Here is an example:

~~~{r}
z <- c(TRUE, TRUE, FALSE)
any(z)
[1] TRUE
all(z)
[1] FALSE
~~~

## 4.2 Defining fuctions

As you become more experienced, you will find yourself needing to perform the same operations over and over. A simple example is computing averages. We can compute the average of a vector `x` using the `sum` and `length` functions: `sum(x)/length(x)`. Because we do this repeatedly, it is much more effiecient to write a function that performs this operation. This particular operation is so coomon that someone already wrote the `mean` function and it is included in vase R. However, you will encounter situations in which the function does noe already exist, so R permits you to write your own. A simple version of a function that computes the average can be defined like this:

~~~{r}
avg <- function(x){
  s <- sum(x)
  n <- length(x)
  s/n
}
~~~

<span style="color:red">
여기서 x는 따로 정의되지 않는 수를 말하나 보다.
</span>

Now `avg` is a function that computes the mean:

~~~{r}
x <- 1:100
identical(mean(x), avg(x))
[1] TRUE
~~~

Notice that variables defined inside a functions are not saved in the workspace. So while we use `s` and `n` when we call `avg`, the values are created and changed only during the call. Here is an illustrative example:

~~~{r}
s <- 3
avg(1:10)
[1] 5.5
s
[1] 3
~~~

<span style="color:red">
값으로 지정된 `s`는 함수 `avg`에 영향을 주지 않았다.
</span>

Note how `s` is still 3 after we call `avg`.

In general, functions are objects, so we assign them to variable names with `<-`. The function 'function` tells R you are about to define a function. The general form of a function definition looks like this:

~~~{r}
my_function <- function(VARIABLE_NAME){
  perform operations on VARIABLE_NAME and alaulate VALUE
  VALUE
}
~~~

The functions you define can have multiple arguments as well as default values. For example, we can define a function that computes either the arithmetic or geometric average depending on a user defined varible like this:

~~~{r}
avg <- function(x, arithmetic = TYRE){
  n <- length(x)
  ifelse(arithmetix, sums(x)/n, prod(x)^(1/n))
}
~~~

We will learn more about how to create functions through experience as we face more complex tasks.

## 4.3 Namespaces

Once you start becoming more of an R expert user, you will likely need to load several add-on packages for some of your analysis. Once you start doing this, it is likely that two packages use the same name for towo different functions. And often these fuctions do completely different things. In tact, you have already encountered this because **dplyr** and the R-base **stats** package define a `filter` function. There are five other examples in **dplyr**. We know this because when we first load **dplyr** we see the followeing message:


~~~{r}
The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union
~~~

So what does R do when type 'filter`? Does it use the **dplyr** function or the **stats** function? From our previous work we know it uses the **dplyr** one. But what if we want to use the **stats** version?

These function live in different *namespaces*. R will follow a certain order when searching for a function in these *namespaces*. You can see the order by typing:

~~~{r}
search()
~~~

